name: CI

on:
  push:
    branches: [ main, 'feat/*', 'fix/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Run lint (root)
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Audit root dependencies
        run: npm audit --audit-level=moderate || true

      - name: Audit server dependencies
        working-directory: ./server
        run: npm audit --audit-level=moderate || true
